[project]
latest="0.0.9"
name = "openmacro"
description = "Official default browser extension for Openmacro. "
why = "Use this extension to have access to the web."
authors = ["amooo-ooo"]
license = "MIT"
readme = "README.md"