[settings]
version = "0.0.9"

[ompi]
readme="README.md"

[setup]
init="__init__.py"
instructions="docs/instructions.md"
docs="docs/docs.md"
source="https://github.com/Openmacro/browser.git"

[dependencies]
gradio_client = "^1.3.0" 
toml = "^0.10"
rich = "^14.0"